version: '3.4'

services:
    nginx_user:
     image: nginx
     ports:
       - 9090:80
     volumes:
       - ./docker/nginx/config/user.conf:/etc/nginx/conf.d/default.conf

    nginx_app:
     image: nginx
     ports:
       - 9091:80
     volumes:
       - ./docker/nginx/config/app.conf:/etc/nginx/conf.d/default.conf

    user:
      image: flan_user
      working_dir: /srv
      build:
        context: docker/php
      volumes:
        - ./user:/srv

    app:
      image: flan_php
      working_dir: /srv
      build:
        context: docker/php
      volumes:
        - ./app:/srv

    dashboard:
      image: pgbi/kong-dashboard:v3.5.0
      depends_on:
        - kong
      command: start --kong-url http://kong:8001
      ports:
        - "8081:8080"

    kong:
      image: "kong:latest"
      command: kong start --run-migrations
      environment:
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: '0.0.0.0:8001'
        KONG_DATABASE: postgres
        KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
        KONG_PG_HOST: db
        KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
        KONG_PG_USER: ${KONG_PG_USER:-kong}
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
      links:
        - db:db
      ports:
        - "8000:8000/tcp"
        - "8001:8001/tcp"
        - "8443:8443/tcp"
        - "8444:8444/tcp"
      restart: on-failure
    db:
      image: postgres:9.5
      environment:
        POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
        POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kong}
        POSTGRES_USER: ${KONG_PG_USER:-kong}
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
        interval: 30s
        timeout: 30s
        retries: 3
      restart: on-failure
      stdin_open: true
      tty: true
